from server import *
emergencyProjects=Work()
emergencyProjects.Hour=9
emergencyProjects.WriteProgram()
emergencyProjects.Hour=10
emergencyProjects.WriteProgram()
emergencyProjects.Hour=12
emergencyProjects.WriteProgram()
emergencyProjects.Hour=13
emergencyProjects.WriteProgram()
emergencyProjects.Hour=14
emergencyProjects.WriteProgram()
emergencyProjects.Hour=17
#emergencyProjects.TaskFinished(False)
emergencyProjects.TaskFinished(True)
emergencyProjects.WriteProgram()
emergencyProjects.Hour=19
emergencyProjects.WriteProgram()
emergencyProjects.Hour=22
emergencyProjects.WriteProgram()
